# https://taskfile.dev

version: 3

tasks:
  build:
    cmds:
      - go build -ldflags "-X github.com/noqqe/relaystation/src/relaystation.Version=`git describe --tags`"  -v .
    sources:
      - "src/relaystation/*.go"
      - "relaystation.go"
    generates:
      - "./relaystation"

  run:
    deps: [build]
    cmds:
      - ./relaystation

  release:
    cmds:
      - git tag
      - read -p "Version v1.1.1 " version ; git tag $version ; docker build -t noqqe/relaystation:$version . ;  docker push noqqe/relaystation:$version
      - git push --tags
    interactive: true

  default:
    cmds:
      - task: build
